CXXSOURCES=./src/lib_json/json_internalarray.inl \
		   ./src/lib_json/json_internalmap.inl \
		   ./src/lib_json/json_reader.cpp \
		   ./src/lib_json/json_value.cpp \
		   ./src/lib_json/json_valueiterator.inl \
		   ./src/lib_json/json_writer.cpp 
CPPFLAGS=-I/home/Administrator/jsoncpp-src-0.50/include
LDFLAGS=
LIBS=
target:
	g++ -c $(CXXSOURCES)  $(CPPFLAGS)
